# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmLearn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmLearn

  pod 'Realm'

end

target 'RealmLearnTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmLearn

  pod 'Realm'

end
